spring:
  datasource:
         url: jdbc:mysql://localhost:3306/shiro
         userName: root
         password: root
  thymeleaf:
         cache: true
         check-template-location: true
         content-type: text/html
         enabled: true
         encoding: utf-8
         mode: HTML5
         prefix: classpath:/templates/
         suffix: .html
  cache:
        ehcache:
          config:  classpath:/ehcache.xml
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
         max-active: 8
         max-wait: -1
         max-idle: 8
         min-idle: 0
    timeout: 0
debug:
   true
mybatis:
  mapper-locations:  classpath:/mapping/*Mapper.xml

logging:
# 打印sql
  level:
     com.example.demo.dao : debug
#     com.example.demo.controller: debug







